# Generated by Django 5.2.dev20241028131012 on 2024-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageHousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eircode', models.CharField(max_length=20, verbose_name='Eircode Output')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALUE')),
            ],
        ),
        migrations.CreateModel(
            name='AverageRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eircode', models.CharField(max_length=20, verbose_name='Eircode')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('average_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Average Rent')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(verbose_name='Date of Sale (dd/mm/yyyy)')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (€)')),
                ('description_of_property', models.CharField(max_length=255, verbose_name='Description of Property')),
            ],
        ),
        migrations.CreateModel(
            name='HousesRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('daft_link', models.URLField(max_length=500, verbose_name='Daft.ie Link')),
                ('property_type', models.CharField(max_length=50, verbose_name='Property Type')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bathrooms')),
                ('recorded_date', models.DateTimeField(blank=True, null=True, verbose_name='Recorded Date')),
            ],
        ),
        migrations.CreateModel(
            name='Propertyrent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ecode', models.CharField(blank=True, max_length=50, null=True)),
                ('Property_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propertysale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ecode', models.CharField(blank=True, max_length=50, null=True)),
                ('Property_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('propertySize', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
