# Generated by Django 5.2.dev20241028131012 on 2024-12-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrent',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='propertyrent',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='propertysale',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='propertysale',
            name='longitude',
        ),
        migrations.AddField(
            model_name='propertyrent',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertysale',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
