# Generated by Django 5.2.dev20241028131012 on 2024-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_propertyrent_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='propertysale',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
