# Generated by Django 5.2.dev20241028131012 on 2024-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(verbose_name='Date of Sale (dd/mm/yyyy)')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (€)')),
                ('description_of_property', models.CharField(max_length=255, verbose_name='Description of Property')),
            ],
        ),
    ]
