# Generated by Django 5.2.dev20241028131012 on 2024-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageHousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('dwelling_status', models.CharField(max_length=100)),
                ('eircode', models.CharField(blank=True, max_length=20, null=True)),
                ('stamp_duty_event', models.CharField(max_length=100)),
                ('type_of_buyer', models.CharField(max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
