# Generated by Django 5.2.dev20241028131012 on 2024-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_averagehouseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagehouseprice',
            name='unit',
            field=models.CharField(default='Default Unit', max_length=10),
        ),
    ]
