# Generated by Django 5.2.dev20241028131012 on 2024-12-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_propertyrent_is_active_propertysale_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyrent',
            old_name='country',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='propertysale',
            old_name='country',
            new_name='county',
        ),
    ]
