# Generated by Django 5.2.dev20241028131012 on 2024-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_averagehouseprice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagehouseprice',
            name='unit',
            field=models.CharField(default='Euro', max_length=10),
        ),
    ]
