# Generated by Django 5.2.dev20241028131012 on 2025-02-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_country_propertyrent_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrent',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertysale',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
