# Generated by Django 5.2.dev20241028131012 on 2024-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_averagehouseprice_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagehouseprice',
            name='eircode',
        ),
        migrations.AddField(
            model_name='averagehouseprice',
            name='eircode_output',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Eircode Output'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='dwelling_status',
            field=models.CharField(max_length=100, verbose_name='Dwelling Status'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='month',
            field=models.CharField(max_length=20, verbose_name='Month of Sale'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='stamp_duty_event',
            field=models.CharField(max_length=100, verbose_name='Stamp Duty Event'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='type_of_buyer',
            field=models.CharField(max_length=100, verbose_name='Type of Buyer'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='unit',
            field=models.CharField(default='Euro', max_length=10, verbose_name='Currency Unit'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Value'),
        ),
    ]
