# Generated by Django 5.2.dev20241028131012 on 2025-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='all_risk_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertysale',
            name='rental_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
