# Generated by Django 5.2.dev20241028131012 on 2024-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_averagehouseprice_eircode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagehouseprice',
            name='eircode_output',
        ),
        migrations.AddField(
            model_name='averagehouseprice',
            name='eircode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='dwelling_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='stamp_duty_event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='type_of_buyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='unit',
            field=models.CharField(default='Euro', max_length=10),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
