# Generated by Django 5.2.dev20241028131012 on 2024-11-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_averagehouseprice_eircode_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousesRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('daft_link', models.URLField(max_length=500, verbose_name='Daft.ie Link')),
                ('property_type', models.CharField(max_length=50, verbose_name='Property Type')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('facilities', models.JSONField(blank=True, null=True, verbose_name='Facilities')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Number of Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Number of Bathrooms')),
            ],
        ),
    ]
