# Generated by Django 5.2.dev20241028131012 on 2025-03-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_propertysale_all_risk_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='all_risk_yield_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
