# Generated by Django 5.2.dev20241028131012 on 2024-11-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_housesrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eircode', models.CharField(max_length=20, verbose_name='Eircode')),
                ('month', models.CharField(max_length=20, verbose_name='Month')),
                ('average_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Average Rent')),
            ],
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='eircode',
            field=models.CharField(max_length=20),
        ),
    ]
