# Generated by Django 5.2.dev20241028131012 on 2024-11-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_averagerent_alter_averagehouseprice_eircode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagehouseprice',
            name='dwelling_status',
            field=models.CharField(max_length=100, verbose_name='Dwelling Status'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='eircode',
            field=models.CharField(max_length=20, verbose_name='Eircode Output'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='month',
            field=models.CharField(max_length=20, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='stamp_duty_event',
            field=models.CharField(max_length=100, verbose_name='Stamp Duty Event'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='type_of_buyer',
            field=models.CharField(max_length=100, verbose_name='Type of Buyer'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='unit',
            field=models.CharField(default='Euro', max_length=10, verbose_name='UNIT'),
        ),
        migrations.AlterField(
            model_name='averagehouseprice',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALUE'),
        ),
    ]
