# Generated by Django 5.2.dev20241028131012 on 2024-11-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_averagehouseprice_dwelling_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesrent',
            name='facilities',
        ),
    ]
