# Generated by Django 5.2.dev20241028131012 on 2024-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_housesrent_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesrent',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
