# Generated by Django 5.2.dev20241028131012 on 2024-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_housesrent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesrent',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='housesrent',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bedrooms'),
        ),
    ]
