# Generated by Django 5.2.dev20241028131012 on 2024-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_housesrent_bathrooms_alter_housesrent_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesrent',
            name='recorded_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recorded Date'),
        ),
    ]
