# Generated by Django 5.2.dev20241028131012 on 2024-11-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_propertysale_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertyrent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ecode', models.CharField(blank=True, max_length=50, null=True)),
                ('Property_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='propertysale',
            options={},
        ),
        migrations.RemoveField(
            model_name='averagehouseprice',
            name='dwelling_status',
        ),
        migrations.RemoveField(
            model_name='averagehouseprice',
            name='stamp_duty_event',
        ),
        migrations.RemoveField(
            model_name='averagehouseprice',
            name='type_of_buyer',
        ),
        migrations.RemoveField(
            model_name='averagehouseprice',
            name='unit',
        ),
        migrations.AlterField(
            model_name='propertysale',
            name='propertySize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertysale',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
